drop table if exists points cascade;
drop table if exists users cascade;

CREATE TABLE users
(
    id              SERIAL          PRIMARY KEY,
    username        VARCHAR(50)     UNIQUE NOT NULL,
    password_hash   TEXT            NOT NULL
);

CREATE TABLE points
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    x        FLOAT NOT NULL,
    y        FLOAT NOT NULL,
    r        FLOAT NOT NULL,
    hit_time TIMESTAMP WITHOUT TIME ZONE,
    hit      BOOLEAN NOT NULL,
    CONSTRAINT pk_point PRIMARY KEY (id),
    CONSTRAINT chk_r_positive CHECK (r > 0),
    CONSTRAINT fk_point_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_points_user_id ON points(user_id);

