drop table if exists point cascade;
drop table if exists users cascade;

CREATE TABLE users (
   id              SERIAL          PRIMARY KEY,
   username        VARCHAR(50)     UNIQUE NOT NULL,
   password_hash   TEXT            NOT NULL
);


CREATE TABLE point
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER                                 NOT NULL REFERENCES users(id),
    x        FLOAT                                   NOT NULL,
    y        FLOAT                                   NOT NULL,
    r        FLOAT                                   NOT NULL,
    hit_time TIMESTAMP WITHOUT TIME ZONE,
    hit      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_point PRIMARY KEY (id)
);